import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  cardContainer: {
    marginLeft: 15,
    paddingLeft: 20,
    paddingRight: 20,
    width: 180,
    backgroundColor: 'white',
    borderRadius: 30,
    paddingTop: 130,
    paddingBottom: 15,
    position: 'relative',
    top: 30,
  },
  title: {
    color: 'black',
    fontWeight: '500',
    textAlign: 'center',
  },
  price: {
    color: '#6A4029',
    fontWeight: '500',
    textAlign: 'center',
  },
  normalPrice: {
    color: '#6A4029',
    fontWeight: '500',
    textAlign: 'center',
    textDecorationLine: 'line-through',
    fontSize: 11,
  },
  image: {
    position: 'absolute',
    width: 140,
    height: 140,
    borderRadius: 15,
    bottom: 60,
    left: 21,
  },
  imagePromo: {
    position: 'absolute',
    width: 140,
    height: 140,
    borderRadius: 15,
    bottom: 80,
    left: 21,
  },
  editButton: {
    width: 30,
    height: 30,
    borderRadius: 30,
    backgroundColor: '#6A4029',
    position: 'absolute',
    zIndex: 2,
    left: 135,
    top: 100,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 2,
  },
  discount: {
    position: 'absolute',
    zIndex: 2,
    backgroundColor: 'white',
    width: 35,
    height: 35,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 30,
    padding: 1,
    borderColor: '#6A4029',
    borderWidth: 1,
  },
  discountText: {
    color: '#6A4029',
    fontWeight: 'bold',
  },
});
